# Generated by Django 2.1.5 on 2019-02-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20190211_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(default=0),
        ),
    ]
