# Generated by Django 2.1.5 on 2019-02-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20190211_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='cinema.TicketStatus'),
        ),
    ]
