# Generated by Django 2.1.5 on 2019-02-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20190211_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('session', 'row', 'seat')},
        ),
    ]
