# Generated by Django 2.1.5 on 2019-02-12 17:23

from django.db import migrations

halls = [
    {
        'name': 'Red hall',
        'row_count': 10,
        'seat_count': 30
    },
    {
        'name': 'Blue hall',
        'row_count': 12,
        'seat_count': 30
    },
    {
        'name': 'White hall',
        'row_count': 15,
        'seat_count': 30
    }
]


def add_halls(apps, schema_editor):
    hall_model = apps.get_model('cinema', 'Hall')

    for hall in halls:
        hall_model.objects.get_or_create(
            name=hall['name'],
            row_count=hall['row_count'],
            seat_count=hall['seat_count'],
        )


def remove_halls(apps, schema_editor):
    hall_model = apps.get_model('cinema', 'Hall')

    for hall in halls:
        inst = hall_model.objects.get(
            name=hall['name'],
        )

        inst.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_auto_20190212_0341'),
    ]

    operations = [
        migrations.RunPython(
            add_halls,
            remove_halls
        )
    ]
